<div class="controls__inputs">
    <label for="userLogin">Имя пользователя:</label>
    <input type="text" id="userLogin" name="userLogin">
    <label for="userPassword">Пароль:</label>
    <input type="password" id="userPassword" name="userPassword">
</div>
<div class="controls__buttons">
    <button type="submit" name="submit" value="signIn">Вход</button>
    <button type="submit" name="submit" value="signUp">Регистрация</button>
</div>
